//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGirard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acce
    {
        public int IdAcces { get; set; }
        public string Login { get; set; }
        public string Mdp { get; set; }
        public string Statut { get; set; }
        public Nullable<int> IdPersonnel { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
