//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGirard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribution
    {
        public int NumDossier { get; set; }
        public int CodeEtape { get; set; }
        public Nullable<int> NumSoustraitant { get; set; }
    
        public virtual Dossier Dossier { get; set; }
        public virtual Etape Etape { get; set; }
        public virtual SousTraitant SousTraitant { get; set; }
    }
}
