//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGirard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDChantierBricchiEntities : DbContext
    {
        public BDChantierBricchiEntities()
            : base("name=BDChantierBricchiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acce> Acces { get; set; }
        public virtual DbSet<Attribution> Attributions { get; set; }
        public virtual DbSet<Candidature> Candidatures { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<Dossier> Dossiers { get; set; }
        public virtual DbSet<Etape> Etapes { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<SousTraitant> SousTraitants { get; set; }
    }
}
