//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGirard
{
    using System;
    using System.Collections.Generic;
    
    public partial class SousTraitant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SousTraitant()
        {
            this.Attributions = new HashSet<Attribution>();
            this.Candidatures = new HashSet<Candidature>();
            this.Etapes = new HashSet<Etape>();
        }
    
        public int NumST { get; set; }
        public string NomST { get; set; }
        public string RueST { get; set; }
        public Nullable<decimal> CodePostalST { get; set; }
        public string VilleST { get; set; }
        public string TelephoneST { get; set; }
        public string FaxST { get; set; }
        public string PortableST { get; set; }
        public string EmailST { get; set; }
        public string NomResponsable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attribution> Attributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidature> Candidatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etape> Etapes { get; set; }
    }
}
